# Generated by Django 4.2.5 on 2023-09-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='due_notes',
            new_name='event',
        ),
    ]
