# Generated by Django 4.2.5 on 2023-09-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0002_rename_due_notes_pipeline_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='due_dates',
            field=models.CharField(max_length=50),
        ),
    ]
