# Generated by Django 4.2.5 on 2023-09-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0003_alter_pipeline_due_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='due_dates',
            field=models.DateField(),
        ),
    ]
